#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: agent-synthesized
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — a failing command inside a pipeline is otherwise silent.
#   - `sha256sum` for lockfile hashing — never hand-rolled (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — always writable inside the sandbox.
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — the sentinel
#     survives reboots but install output dirs may not on fresh tmpfs, so never
#     skip on a clean directory.
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.
#   - run_install has an npm ERESOLVE fallback (--legacy-peer-deps) + a FATAL
#     marker (D-12.1) — a scaffold with a lagging peer range must not silently
#     leave node_modules empty and hang the preview on "Waiting to bind".
#
# Multi-match (D-05/D-06): this project's root carries BOTH a compose file
# (docker-compose.yml, services: db + app) AND a Next.js manifest
# (package.json + next.config.ts), so it matched the `compose` entry and the
# `react-next` entry at once. Per D-05 that is agent fallback, not a
# mechanical merge. The classification question the `compose` catalog entry
# asks first (#668) — does this compose file run the app, or only its
# datastores? — resolves to Shape A here: the `app` service has a `build:`
# directive and its own Dockerfile runs the generated code, so compose owns
# the whole stack and `docker compose up --build` is the wrapper's entire
# exec command, exactly as the `compose` entry's Shape A prescribes. The
# `react-next` entry's env preamble / pre-exec config patch do not apply:
# the app container runs `next start` (production mode, see Dockerfile CMD),
# not `next dev`, so there is no dev-server allowedDevOrigins / HMR host
# concern to patch.

set -euo pipefail

# === Bash version guard ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === Single-instance guard ===
# Multiple platform paths can invoke the wrapper concurrently (sandbox setup,
# preview open, verify pre-flight) — observed as two `docker compose up --build`
# trees racing in one sandbox. Second invocation exits 0 quietly: the first
# boot is authoritative and callers poll the port, not this process.
exec 200>/tmp/pivota-dev.lock
if ! flock -n 200; then
  echo "[pivota] start-dev.sh already running (lock held) — exiting; poll the ready port instead" >&2
  exit 0
fi

# === Already-up fast path (#219) ===
# The flock above stops two invocations racing. It does NOT stop the far more
# common SEQUENTIAL double-boot: in one verify run the platform starts the
# stack, the init-dev-server boot-smoke starts it again and then kills it, and
# verify-work's step 1 finds a dead port and starts it a third time. Each
# `docker compose up --build` destroys and recreates every container, so
# mid-verify the app's ports go down for ~3s — which reads as an app crash to
# whoever is watching the preview.
#
# So: if this project's ready ports are already answering AND nothing has
# changed that a restart would pick up, the boot is already done. Exit 0 and
# let the caller poll the port, exactly as the lock branch does.
#
# "Nothing has changed" is TWO facts, and both are load-bearing:
#   * the resolved compose config is byte-identical, and
#   * git HEAD has not moved.
# HEAD is what keeps this from re-introducing the stale-preview class: the
# compose app's image bakes the source and serves the OLD code until it is
# rebuilt, so a new commit MUST fall through to the full boot below.
#
# Escape hatch: PIVOTA_DEV_FORCE_RESTART=1 always does the full boot.
READY_PORTS="3000"
DEV_STATE="/tmp/pivota-dev-boot-state"
dev_boot_state() {
  # Cheap, deterministic, and quiet. `compose config` resolves env/overrides,
  # so it changes whenever anything that would alter a container changes.
  # Missing docker or no compose file -> the compose half is simply empty.
  printf '%s|%s' \
    "$(git rev-parse HEAD 2>/dev/null || echo no-git)" \
    "$(docker compose config 2>/dev/null | sha256sum 2>/dev/null | cut -d' ' -f1)"
}
dev_ports_answering() {
  local p ok=1
  [ -n "${READY_PORTS// /}" ] || return 1
  for p in $READY_PORTS; do
    if (exec 3<>"/dev/tcp/127.0.0.1/$p") 2>/dev/null; then exec 3>&-; ok=0; fi
  done
  return $ok
}
dev_compose_healthy() {
  # Only meaningful for a compose app. `config --services` is the presence
  # test that actually works: it succeeds exactly when a compose file exists
  # AND parses (a filename glob exits non-zero on the other spelling).
  docker compose config --services >/dev/null 2>&1 || return 0   # not compose -> nothing to check
  local rows
  # Deliberately NOT `docker compose ps --format '<go template>'`: a Go
  # template's double-brace syntax collides with this file's own placeholder
  # syntax, so the renderer would eat it at generation time. Plain table
  # output, header dropped.
  rows="$(docker compose ps --all 2>/dev/null | tail -n +2 || true)"
  [ -n "$rows" ] || return 1
  # A non-zero exit, a restart loop or a failing healthcheck all mean the
  # stack is not one we may adopt. `Exited (0)` is fine — a one-shot init or
  # migrate service legitimately finishes.
  ! printf '%s\n' "$rows" | grep -qiE 'restarting|unhealthy|exited \([1-9]'
}
if [[ "${PIVOTA_DEV_FORCE_RESTART:-}" != "1" ]] \
   && [[ -f "$DEV_STATE" ]] \
   && [[ "$(cat "$DEV_STATE" 2>/dev/null)" == "$(dev_boot_state)" ]] \
   && dev_ports_answering \
   && dev_compose_healthy; then
  echo "[pivota] dev stack already up on port(s) ${READY_PORTS} with unchanged compose config and HEAD — skipping restart (set PIVOTA_DEV_FORCE_RESTART=1 to override)"
  exit 0
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
# SSE chat panel sees output live AND a file exists for scrollback / replay.
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: agent-synthesized)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# Compose services control their own bind addresses via the `ports:` block in
# docker-compose.yml — there is no env-var lever the wrapper can pull to force
# 0.0.0.0 binding for child containers, and this project's `app` service
# already publishes `3000:3000` (not loopback-restricted), so the preview
# proxy can reach it. The per-stack env block is intentionally EMPTY here.

# === D-11.3: .env.example -> .env seed (platform-injection-safe) ===
# Seed .env from .env.example for first boot, but NEVER let an .env.example
# placeholder shadow a variable the platform already injected into the sandbox
# environment. Any KEY already set in the environment (DATABASE_URL,
# POSTGRES_*/MYSQL_*, REDIS_URL, PIVOTA_*, plus PORT/NODE_ENV from the preamble
# above) is dropped from the copy so the injected value wins. See
# references/runtime-environment.md §3. NOTE: this project's own
# docker-compose.yml already sets DATABASE_URL on the `app` service pointing at
# the compose `db` service name, so the seeded .env (used only by anything run
# natively outside compose, e.g. `prisma generate`) never needs to win over it.
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] seeding .env from .env.example (preserving platform-injected vars)"
  while IFS= read -r line || [[ -n "$line" ]]; do
    trimmed="${line#"${line%%[![:space:]]*}"}"   # left-trim for the test only
    if [[ "$trimmed" == \#* || -z "$trimmed" || "$trimmed" != *"="* ]]; then
      printf '%s\n' "$line"; continue            # keep comments / blanks / non-assignments
    fi
    key="${trimmed#export }"; key="${key%%=*}"; key="${key//[[:space:]]/}"
    if [[ -n "${!key+x}" ]]; then
      printf '# [pivota] %s omitted — provided by platform environment\n' "$key"
      continue
    fi
    # D-11.5: sanitize the copied assignment. Strip unquoted inline `#`
    # comments (docker compose's own .env parser passes them through as part
    # of the value) and replace CHANGE_ME-style placeholders with a generated
    # 48-char secret.
    if [[ "$line" != *\"* && "$line" != *\'* ]]; then
      line="$(printf '%s' "$line" | sed -E 's/[[:space:]]+#.*$//')"
    fi
    value="${line#*=}"
    value_lc="$(printf '%s' "$value" | tr '[:upper:]' '[:lower:]')"
    if [[ "$value_lc" == change_me* || "$value_lc" == changeme* ]]; then
      generated="$(head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9')"
      printf '%s=%s\n' "$key" "${generated:0:48}"
      echo "[pivota] generated random value for placeholder $key" >&2
    else
      printf '%s\n' "$line"
    fi
  done < .env.example > .env
fi

# === D-11.6 (#510): load .env into THIS process's environment ===
# `set -a` + `.` is POSIX, handles quoting/escapes correctly, and cannot be
# got wrong the way a hand-rolled `export "$line"` parser can (quotes land
# inside the value). Platform-injected values still win: the keys the file
# defines are snapshotted first and re-applied after, and ONLY those keys.
if [[ -f .env ]]; then
  echo "[pivota] loading .env into the environment"
  PIVOTA_ENV_KEEP="$(mktemp)"
  while IFS= read -r _pivota_key; do
    if [[ -n "${!_pivota_key+x}" ]]; then
      declare -p "$_pivota_key" 2>/dev/null || true
    fi
  done < <(sed -nE 's/^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)=.*/\2/p' .env | sort -u) \
       > "$PIVOTA_ENV_KEEP"
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a
  # shellcheck disable=SC1090
  . "$PIVOTA_ENV_KEEP"
  rm -f "$PIVOTA_ENV_KEEP"
  unset PIVOTA_ENV_KEEP _pivota_key
fi

# === D-11.7 (#510): workspace-hoisted binaries on PATH ===
# npm workspaces hoist every package's bin to the ROOT node_modules/.bin.
# Harmless when the directory does not exist yet (this project is a single
# package anyway, but this is templated behavior shared by every wrapper).
export PATH="$PWD/node_modules/.bin:$PATH"

# === Pre-exec snippet ===
# None needed: this is a Shape A compose project — the app's own Dockerfile
# installs deps, generates the Prisma client and builds inside the image
# build step, and the compose service's own `command` runs
# `prisma migrate deploy && tsx src/data/seed.ts && next start` (idempotent
# seed per references/runtime-environment.md §3). No host-side install or
# config patch belongs in the wrapper.

# === D-12: idempotent install via lockfile hash + presence check ===
# None for compose (D-12 n/a): compose images come pre-built via the `build:`
# directive, and docker's own layer cache handles incremental rebuilds. No
# lockfile hash / sentinel branch applies here — this section intentionally
# falls through with both LOCK_FILE_PATH and INSTALL_CMD empty.
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH=""
INSTALL_PRESENCE_CHECK=""
INSTALL_CMD=''   # empty: docker compose up --build handles the image build

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  local rc=0
  bash -c "$INSTALL_CMD" || rc=$?
  if (( rc == 0 )); then
    return 0
  fi
  if [[ "$INSTALL_CMD" == *"npm "* ]]; then
    echo "[pivota] WARN install failed (exit=$rc) — retrying with --legacy-peer-deps (peer conflict force-resolved; runtime incompatibility possible)"
    local rc2=0
    npm install --legacy-peer-deps || rc2=$?
    if (( rc2 == 0 )); then
      echo "[pivota] WARN install succeeded via --legacy-peer-deps fallback — a dependency's peer range is unsatisfied; fix package.json (this is a real bug, not just a warning)"
      return 0
    fi
    rc=$rc2
  fi
  echo "[pivota] FATAL install failed (exit=$rc) — dev server cannot start; resolve the dependency conflict in the manifest" >&2
  return "$rc"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
# Final-attempt exit code propagates the INNER command's exit code, not a
# fixed 1, so the caller (platform / Daytona) can distinguish "wrapper bug"
# from "user command failed with N".
#
# `--build` is load-bearing, not an optimization: pivota projects are
# actively modified between boots (execute phases, gap-closure fixes). A
# plain `docker compose up` reuses the cached image whenever one exists, so a
# source fix that is already committed keeps crash-looping in a stale
# container. Docker's layer cache keeps the rebuild cheap when nothing changed.
EXEC_CMD='docker compose up --build'

# #219: record what this boot is FOR, so the fast path at the top of the file
# can tell "already running the same thing" from "running something stale".
# Written before exec, not after: exec blocks for the life of the server, and
# a state file that only appears on shutdown is a state file that never
# appears. Writing it early cannot cause a bad adopt — the fast path also
# requires the ready ports to answer, which a failed boot never satisfies.
dev_boot_state > "$DEV_STATE" 2>/dev/null || true

ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (the regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
